apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-quarkus-helloworld
build:
  artifacts:
  - image: franroa/skaffold-quarkus-helloworld
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/app.yaml
